language: node_js
node_js:
  - "0.10"
after_success:
  - "npm run jsdoc"
notifications:
  slack:
    secure: jOhhMsUyxLgjn8ckB5fMp4Hrw6ZTKG9EnLBaj2CEVG2cfTnjH2O+E8REtDWTmItzlyJJne1BNzC4Mqygbs/Og0xNtnBJdpEXDxH9ouo+MRr6CUlZRTYQLy7NhF9FbWujcNlmBK55SNvABfc/vuiJlhq8uAsl2g09AH3ujbh3p0Q=
addons:
  artifacts:
    key:
      secure: cNwUpMfjDgYq196ZtsQoLQ0vW45QlU7kew21h6vBkfJPY+L8Zgi0TnIXzk2wAhUun2MKHwylL1oXGIHhXejiX1dBHWBi5ZvLmNxZrLRqg1GG+KkWneZGKErtnReG6dqa5MDp09Iq0V3qTaxNJKTEHvp/6mgAb/tdJWQHPtIPXwo=
    secret:
      secure: CVrVW9wudXHvsTHlSuL152g37Up3pv/seRASiSMoUnYL7gi/0K/CAtXKDujdwX98N2x3PQRk/U7Ao1/DjGZs6jlVtbmX4LAC87sEkJMJ2UrLjiw8NP2YMFiy+YFnpA7Wz7qvxWhm3Ckzf4XniRFsJaIdowdKpafxXJ0wK9yzlH8=
    bucket: tsertkov-artifacts
    debug: true
