language: node_js
node_js:
- '0.10'
after_success:
- npm run jsdoc
- cat artifacts/coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
notifications:
  slack:
    secure: jOhhMsUyxLgjn8ckB5fMp4Hrw6ZTKG9EnLBaj2CEVG2cfTnjH2O+E8REtDWTmItzlyJJne1BNzC4Mqygbs/Og0xNtnBJdpEXDxH9ouo+MRr6CUlZRTYQLy7NhF9FbWujcNlmBK55SNvABfc/vuiJlhq8uAsl2g09AH3ujbh3p0Q=
deploy:
- provider: s3
  access_key_id:
   secret: NfkcUUWHRqNUxXwqLIsnaxwImmzXBZtkbE4DkkwCEvpnoNdmE5vt4OKFPFQxMXyHkOM9SWghaDAYyp/PmHenEAmEtNEfT4vyBdKDnvZPBqwGwxQn4C6cJdHVxWHF0L3HT5pOJVbhJkOli9oHh4y0hXp2xlcR6PNrJXXaoc4Odec=
  secret_access_key:
    secure: US+0riApTPSNg8HjBGJ7Nj+HxGfkoaAAUkhoJEGulSx/hBYUTfg8LmndI5KVcQGCC5GAU7mwlUsjfb2pLVl4HIGf3rOKawh8zSiReB9o+gdqSgAMLiCleFIKn8Eo16Czac5ohTyU9+LUfFdvLMeGL9XMcPn9kaGjmSFa9b+LOHc=
  bucket: tsertkov-artifacts
  local-dir: artifacts
  upload-dir: dotpath-resolve/master
  acl: public_read
  skip_cleanup: true
  region: eu-central-1
  endpoint: s3.eu-central-1.amazonaws.com
  on:
    branch: master
- provider: s3
  access_key_id:
   secret: NfkcUUWHRqNUxXwqLIsnaxwImmzXBZtkbE4DkkwCEvpnoNdmE5vt4OKFPFQxMXyHkOM9SWghaDAYyp/PmHenEAmEtNEfT4vyBdKDnvZPBqwGwxQn4C6cJdHVxWHF0L3HT5pOJVbhJkOli9oHh4y0hXp2xlcR6PNrJXXaoc4Odec=
  secret_access_key:
    secure: US+0riApTPSNg8HjBGJ7Nj+HxGfkoaAAUkhoJEGulSx/hBYUTfg8LmndI5KVcQGCC5GAU7mwlUsjfb2pLVl4HIGf3rOKawh8zSiReB9o+gdqSgAMLiCleFIKn8Eo16Czac5ohTyU9+LUfFdvLMeGL9XMcPn9kaGjmSFa9b+LOHc=
  bucket: tsertkov-artifacts
  local-dir: artifacts
  upload-dir: dotpath-resolve/develop
  acl: public_read
  skip_cleanup: true
  region: eu-central-1
  endpoint: s3.eu-central-1.amazonaws.com
  on:
    branch: develop
